version: '3.8'  # Compose 버전
services:        # 실행할 컨테이너 정의
  web:
    image: nginx
    ports:
      - "8080:80"   # 호스트:컨테이너 포트 매핑
    volumes:
      - ./web:/usr/share/nginx/html  # 로컬 디렉토리를 컨테이너에 마운트
  db:
    image: mysql:5.7
    platform: linux/amd64
    environment:   # 환경 변수 설정
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: example_db
volumes:
  db-data:  # MySQL 데이터 볼륨
