apiVersion: v1          # 리소스의 API 버전 (v1은 Service에 사용됨)

kind: Service           # Kubernetes 리소스의 종류 (여기서는 Service)

metadata:               # 리소스의 메타데이터 정보
  name: web-service     # Service의 이름 (고유 식별자)
  
spec:                   # Service의 스펙 정의
  selector:             # Service가 연결할 Pod를 선택하는 기준
    app: web            # app: web 라벨이 있는 Pod와 연결
  ports:                # Service에서 사용할 포트 정의
    - protocol: TCP       # 네트워크 프로토콜 (기본값은 TCP)
      port: 80           # Service가 외부에 노출할 포트
      targetPort: 80     # Service가 Pod 내부의 컨테이너와 연결할 포트
  type: NodePort         # Service의 유형 (NodePort는 외부 접근 가능)
